export async function getServerSideProps({ res }) {
  const base = process.env.NEXT_PUBLIC_URL || 'https://matkassepriset.vercel.app';
  const pages = [{"path":"","priority":"1.0","changefreq":"daily"},{"path":"/om-oss","priority":"0.5","changefreq":"monthly"},{"path":"/kontakt","priority":"0.4","changefreq":"monthly"},{"path":"/integritetspolicy","priority":"0.3","changefreq":"yearly"},{"path":"/vegansk","priority":"0.8","changefreq":"weekly"},{"path":"/keto","priority":"0.8","changefreq":"weekly"},{"path":"/familj","priority":"0.8","changefreq":"weekly"},{"path":"/student","priority":"0.8","changefreq":"weekly"},{"path":"/ekologisk","priority":"0.8","changefreq":"weekly"},{"path":"/jamfor/linas-matkasse-vs-middagsfrid","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/linas-matkasse-vs-hellofresh","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/linas-matkasse-vs-simple-feast","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/linas-matkasse-vs-mathem-matkasse","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/linas-matkasse-vs-arstiderna","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/linas-matkasse-vs-city-gross-matkasse","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/middagsfrid-vs-hellofresh","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/middagsfrid-vs-simple-feast","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/middagsfrid-vs-mathem-matkasse","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/middagsfrid-vs-arstiderna","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/middagsfrid-vs-city-gross-matkasse","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/hellofresh-vs-simple-feast","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/hellofresh-vs-mathem-matkasse","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/hellofresh-vs-arstiderna","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/hellofresh-vs-city-gross-matkasse","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/simple-feast-vs-mathem-matkasse","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/simple-feast-vs-arstiderna","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/simple-feast-vs-city-gross-matkasse","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/mathem-matkasse-vs-arstiderna","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/mathem-matkasse-vs-city-gross-matkasse","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/arstiderna-vs-city-gross-matkasse","priority":"0.7","changefreq":"weekly"}];
  const xml = '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' +
    pages.map(function(p) { return '<url><loc>'+base+p.path+'</loc><lastmod>2026-06-24</lastmod><changefreq>'+p.changefreq+'</changefreq><priority>'+p.priority+'</priority></url>'; }).join('') +
    '</urlset>';
  res.setHeader('Content-Type', 'application/xml');
  res.setHeader('Cache-Control', 's-maxage=86400, stale-while-revalidate');
  res.write(xml); res.end();
  return { props: {} };
}
export default function Sitemap() { return null; }